name: Reusable Workflow

on:
  workflow_call:
    inputs:
      repo:
        required: true
        type: string

jobs:
  Build:
    runs-on:
      group: ibm-vm-135
      labels: 135
    outputs:
      app: ${{ steps.get-app.outputs.app }}
    steps:
      - name: Check out repository code 
        uses: actions/checkout@v4
        with:
          ref: master-dev

      - name: List files
        run: ls -a

      - name: Get app name
        id: get-app
        shell: bash
        run: |
          app=$(echo "${{ inputs.repo }}" | awk -F'/' '{print $2}' \
              | tr '[:upper:]' '[:lower:]' | tr -d '[:space:]')
          app=${app%-}
          echo "app=$app"
          echo "app=$app" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: docker build -t ${{ steps.get-app.outputs.app }} .

  Deploy:
    needs: Build
    runs-on:
      group: ibm-vm-135
      labels: 135
    steps:
      - name: list images
        run: docker images
      - name: Stop list running containers
        run: docker ps
      - name: Stop current container (ignore if not running)
        run: docker stop ${{ needs.Build.outputs.app }} || true
      - name: prune container
        run: docker container prune -f
      - name: Start application
        run: docker run -d --rm --name ${{ needs.Build.outputs.app }} -p 3000:3000 ${{ needs.Build.outputs.app }}

  Cleanup:
    needs: Deploy
    needs: Build
    runs-on:
      group: ibm-vm-135
      labels: 135
    steps:
      - name: Prune unused docker resources
        run: docker system prune -f
